import Layout from "../components/layout";
import Head from "next/head";
import { TOKEN, DATABASE_ID } from "../config";

export default function Projects() {
    return (
        <Layout>
            <Head>
                <title>이건혁 포트폴리오</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className="flex min-h-screen flex-col items-center justify-center text-gray-600 body-font">
                <h1>나에 대한 소개 페이지입니다.</h1>
            </section>
        </Layout>
    );
}

export async function getStaticProps() {
    const options = {
        method: 'POST',
        headers: {
        Accept: 'application/json',
        'Notion-Version': '2022-06-28',
        'Content-Type': 'application/json',
        Authorization: `Bearer ${TOKEN}`,
        },
        body: JSON.stringify({page_size: 100})
    };
    
    const response = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, options);

    const result = await response.json();

    console.log(result);

    return {
      props: {}, // will be passed to the page component as props
    }
}